//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoTestEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todos
    {
        public long id { get; set; }
        public string text { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> completedAt { get; set; }
    }
}
